### ISSUE TITLE
how to run the code?

### ISSUE THREAD

**Issue by Joy-liningqiao** [smiles724/3D-Transformer#1]
It seems I didnot find the main function entrance of the code.. Is there anyway I can run it?

**Comment by smiles724** [comment]
Sorry about the late reply. We provide concrete usage of how to run the model with what is the input and what is expected to be the output. Sure, we did not upload all our training scripts. The reason is that we are still improving our work in the past few weeks. The most significant difference between the current version and the previous one is that we add motifs into the input. Moreover, we delete the experiments conducted on the material datasets, since we found that ICLR reviewers cared little about the superiority of our model in the field of the material dataset. Thus, we close the download link of our material datasets, which you can download from somewhere else if you are interested. 

Thanks again for your attention on our project.
